addons:
  postgresql: 9.5
after_success:
- bundle exec codeclimate-test-reporter
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
dist: trusty
language: ruby
rvm:
- 2.5.0
script:
- bundle exec rails db:migrate
deploy:
  provider: heroku
  api_key:
    secure: 1UEdYwzBzJRPbmqVNwLqHksrnTKX5q2qRIZPnxVvLlGmORO9J+fCLgKPfw9ntOueXu80+PS6sNLn+8rDnsB3QMfGdbBfliBtXShtFwfxrVG1lubiAoi7iZTTKq7QOO5DBJLH2tMRIjxweV7F3VT4Xbim8IoO+krsPcgdya3IkhIc6H7OgnemitS9fgoPvqTgz2XmsHWhon+SHpIU4rAJM8zrK6OzywYSqbbXQYd/NosRpJxMFjDUcaEfr8VN09aqCME6uzGwFOKk8EM0syWpBBIXojHgb4ijMH7iORr0vq0fqNPGUlZz3Dk5JjBY2JL6jREwtH/JT205j3wCdewTGTS2QVj90aqXofBevPVZwMQ3g/8BwG4jRT9SHG1De+VW4sa2Rl+PrSa8g5e0TKj/CZK+h8RpdMLtNKRPnVEx2lxLJuP8fYvD970mgLAkO9mIQKpQw28Y/HjKxOhrCrp7OkukaO6dfnmhvOP63gljzTBavGUqQM4zOxfRu6vfsYavXEhQpnZdKBj0LEmnmxNyZUL4qzJSe/cDvrH7uvATWnl7G7oHdLKNFlBBvfgzEJ9AYVPbawH+y2KJu4UUmLXrtncDAhGrhjHSjDiEjdRGQIFzjL50ddbFfoSpWaD8WLbDxRyZ5+38DI/+sMtcoDntmlenMHGoPLd9uA1AyCTDbZk=
  app:
    master: travistestdemo
  run:
  - rake db:migrate
  - rake cleanup
