addons:
  postgresql: 9.5
after_success:
- bundle exec codeclimate-test-reporter
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
dist: trusty
language: ruby
rvm:
- 2.5.0
script:
- bundle exec rails db:migrate
deploy:
  provider: heroku
  api_key:
    secure: 0s36/9UACE768GsK7xmqRopNPwjEYq5hM0Q8nnxupg/z0jGSNxaraMk7QcKysEbP1H8u1ft0E9Rw6CRVURe02+z42a/aHHGWFP/XfGUTm8oJmsHRMk2xq/G5OwImlDH3MjQ1BV6x/+1Z6zLOovpsH7j/uscOASUr8+hbP11Zu3c3VHtkJDzpBmGSBreSZId6OAr1KeSqcXCXnb/cjdC6j1Kayk4uOxDX3d1AKm5m5sXY3f0R7rcbbZmRLvMfTITQwiWGXZzBaoui1Ru2V6nfKuW0KQGQgdrKdP1OEsjVHQdtE1pURPjjwYkS+Fx8iwamYI14gMpElvrtyy/28MEqcIO3Kj6lHNVPTjxq1eeFh2+am7Y7zTbGBlmddJX/SKfI0SBkMOSbbKcW9JQSvjrCY84lqdgTVFiSa+68NW+ETO28+hMgVKxDLReuxsZqtFv7SuNUO2CbAzUD3vNINFd4A0p+8e9vtmYjB0pOMpcTlEzNCFYNjUOA3W4jU6hKRReTlAMbd5Qzi7BxrrV1jUpmyviqFLexU5870LoirWR78zKH0VXOqXk2gySTg06SqPVTdR9cE0ypsYHNPdXI4K1p9/22rcMrXnUmi+RrA/rPseNxWAsYpu455OMBaqlutUwvg1YkoIFk0Hp3HEmZppRNoSe7nEReC3ct28w6CHSneSY=
  app:
    master: travistestdemo
  run:
  - rake db:migrate
  - rake cleanup
